"""Real hardware backend for the station mini PC (Linux).

NOT IMPLEMENTED YET — deliberately. The implementation depends on Phase 0
dock characterization (tools/dock_characterize.sh), which determines for each
dock:

  * how each physical slot enumerates (separate USB devices vs. LUNs)
  * whether serial/model pass through the bridge truthfully
  * which SMART/NVMe health reads work (smartctl -d type, nvme-cli)
  * which wipe commands actually reach the drive (sanitize, format,
    ATA secure erase, or zero-overwrite fallback)
  * hot-plug and mid-wipe disconnect behavior

Planned implementation sketch:
  * udev monitor (pyudev) for block device add/remove events
  * slot mapping: walk /sys ancestry to the USB port path, look it up in the
    allowlist file (slots.toml) generated by the setup wizard
  * identity: smartctl -i --json / nvme id-ctrl
  * health: smartctl -A --json / nvme smart-log
  * wipes: nvme sanitize / nvme format / hdparm security-erase /
    dd zero overwrite with progress, per the characterization results
  * verification: full or sampled read-back for overwrite/block methods,
    completion-status plus sampling for crypto erase
"""
from __future__ import annotations

from .base import HardwareBackend


class LinuxBackend(HardwareBackend):  # pragma: no cover - placeholder
    def __init__(self, *args, **kwargs):
        raise NotImplementedError(
            "The Linux hardware backend requires Phase 0 dock characterization "
            "results. Run tools/dock_characterize.sh on the station with "
            "sacrificial drives first.")

    def start(self, on_insert, on_remove): ...
    def read_identity(self, slot_id): ...
    def read_health(self, slot_id): ...
    def supported_wipe_methods(self, slot_id): ...
    def wipe(self, slot_id, method, progress): ...
    def verify(self, slot_id, method, progress): ...
